### ISSUE TITLE
Can't modify whitelist/blacklist

### ISSUE THREAD

**Issue by sibrus** [dashkb/round#26]
Note: All my issues are going to be from Ubuntu 14.04 x64.

Repro:

1. Create a whitelist/blacklist. The one I made has 3 allowed genres, 1 allowed artist, 1 blocked artist.
2. Save it with a name.
3. From /admin, click any "Remove" button
4. Nothing happens :(

**Comment by jlogsdon** [comment]
Working for me. It takes up to 2 seconds for the removal to reflect, as we're polling the Access Lists on that page every 2 seconds. Are there any errors in either the JS Console or the Command Line where you ran `foreman start`?

**Comment by jlogsdon** [comment]
I did just push up a small fix where a possible null value could have caused issues, but you wouldn't have even seen the admin page in that case.

**Comment by sibrus** [comment]
"works for me" is exactly what I was worried about. I have some suspicion that things don't "just work" in a linux environment. (See my feature-ubuntu branch for the set of changes I had to make to just get the thing to run.) 

I've had a few other issues besides this which I haven't reported yet. Less than 30 minutes into testing I got my system into a completely (and permanently) unusable state - at first it would not play anything, and then, after doing "foreman start", the server seems to start and process requests, but the actual UI never loads (the loading bar just hangs at 99%).

I've confirmed that wiping my db and redis db and re-importing my music puts everything back to normal. As such, I'm going to attach a tarball of my db directory. Unfortunately I don't have enough knowledge of this app to debug this myself.

**Comment by sibrus** [comment]
Err, can't attach files here. Tarball is here: http://boston.sibrus.net/tmp/db-borked-2015-07-12.tar.gz

**Comment by jlogsdon** [comment]
If you can give me any error messages from the JS Console that would help immensely. My NUC is arriving tomorrow so I'll start working on the Ubuntu side of things then.

**Comment by jlogsdon** [comment]
Can you do me a favor and try everything with the `Fake` device instead of `VLC`? It may be directly related to issues with the VLC device.

**Comment by sibrus** [comment]
My database should reproduce this error reliably. Here's what's in the JS console (sorry, comes out ugly when I copy-paste):

Unhandled promise rejection TypeError {stack: (...), message: "Cannot read property 'name' of null"} bundle.js:1939(anonymous function) bundle.js:1939module.exports bundle.js:2277queue.(anonymous function) bundle.js:2222run bundle.js:2210listner bundle.js:2214
Unhandled promise rejection TypeError {stack: (...), message: "Cannot read property '_currentElement' of null"} bundle.js:1939(anonymous function) bundle.js:1939module.exports bundle.js:2277queue.(anonymous function) bundle.js:2222run bundle.js:2210listner bundle.js:2214

**Comment by sibrus** [comment]
I've confirmed that the whole "UI doesn't load and everything is broken" state happens exactly the same with the fake player. Whether using the VLC backend had anything to do with getting into this state I'm not sure.

**Comment by jlogsdon** [comment]
Okay. let me look at that database.

**Comment by jlogsdon** [comment]
I pushed some changes up to the master branch. Web runs on port 5100 instead of 5000 now, and the JS source maps work for friendlier logs.

You shouldn't ever see the progress get to ~99% and then stop anymore. That was an issue with the whitelist/blacklist issues in the other thread.

**Comment by jlogsdon** [comment]
And the backends should have no impact on anything, they cannot write anywhere (either the sqlite database or redis) and are simply interfaces to play the tracks through.

**Comment by jlogsdon** [comment]
Also added logging of SQL queries to `log/queries.log`, and the Player service syncs output instead of flushing in batches.

**Comment by jlogsdon** [comment]
This _should_ be resolved now. Reopen if not.
