### ISSUE TITLE
When whitelist/blacklist exists, can't skip tracks

### ISSUE THREAD

**Issue by sibrus** [dashkb/round#27]
Basically, create a whitelist/blacklist like in issue #26 

At this point, the skip button just causes the music to stop. However, tracks advance normally once they end.

**Comment by jlogsdon** [comment]
Also works for me. Anything show up in the JS or Command line consoles?

**Comment by jlogsdon** [comment]
Alright I think I tracked this down to the query I build. It's currently possible to setup the access lists to never return a track if the Whitelisted Artists do not belong to any of the Whitelisted Genres. I'm thinking the query for this should change from:

```sql
SELECT * FROM tracks WHERE
  (`genre_id` IN (whitelisted_genres) AND
    `artist_id` IN (whitelisted_artists) AND
    `genre_id` NOT IN (blacklisted_generes) AND
    `artist_id` NOT IN (blacklisted_artists))
```

to

```sql
SELECT * FROM tracks WHERE
  (`genre_id` IN (whitelisted_genres) AND
    `genre_id` NOT IN (blacklisted_generes))
  OR
  (`artist_id` IN (whitelisted_artists) AND
    `artist_id` NOT IN (blacklisted_artists))
```

so they act as separate lists.

**Comment by jlogsdon** [comment]
Actually, that may not work right. We'll have to work this out at some point...

**Comment by sibrus** [comment]
Try this one on for size:

```
SELECT * FROM tracks WHERE
  (`genre_id` IN (whitelisted_genres) OR 
    `artist_id IN (whitelisted_artists))
  AND `genre_id` NOT IN (blacklisted_generes)
  AND `artist_id` NOT IN (blacklisted_artists)
```

This should basically apply the whitelist first (both genres and artists) and then remove everything in the blacklist (either genres or artists)

It's still not perfect, but I think it's close. (I'd prefer it if whitelisting an artist "overrides" blacklisting the genre that the artist is in)

**Comment by jlogsdon** [comment]
I have an idea actually. When adding something to either list it will check how many tracks are available with the change. If it's 0 we don't save it and show a message.

**Comment by sibrus** [comment]
That's a good idea, or something to that effect. 

On a related note, it seems like you're always editing the "current" whitelist/blacklist, and your changes are being applied immediately. This is sometimes what you want, but not always. 

Consider the use case: "we want to collaboratively create the Saturday night whitelist/blacklist, but we don't want to mess with the music happening right now because it's Saturday aftrnoon"

If something like this were done, you'd probably want the guard when you apply the whitelist/blacklist, as opposed to during every edit.

**Comment by jlogsdon** [comment]
If that's what people want I can do that, it'll take a bit to add though. It's definitely doable, though.

**Comment by jlogsdon** [comment]
Alright there's no a "Clear list" button on the Admin page for quickly removing everything. And blacklisting or whitelisting anything will check to make sure at least 1 track is selectable with the change, and refuse it if not. Should prevent bad states. Note that if the list you saved was invalid its still possible to load. I'm not going to do anyting about that until I work on the different way of managing them.

**Comment by sibrus** [comment]
On a totally unrelated note, I saw you're going to this: https://www.facebook.com/events/485553444930486/ so I'm going too :P

Are you going to be there for the workshop part?

On another note, why can't I reach you on your cell?

**Comment by jlogsdon** [comment]
This should be resolved. Reopen if not.
