### ISSUE TITLE
VLC backend: time reporting is a bit bugged

### ISSUE THREAD

**Issue by sibrus** [dashkb/round#28]
When using the VLC backend (under VLC media player 2.1.4 Rincewind), the current position of the track is mostly correct, but it sporadically reports the position as 0:01 and then goes back to the correct position. Basically has the effect of occasionally "flickering" to the 0:01 position every few seconds.

**Comment by jlogsdon** [comment]
Use the Audite backend. Will likely rip out VLC entirely as its not all that stable.
